version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./api:/usr/src/app
      - ./db/FinanceManager.sqlite3:/usr/src/FinanceManager.sqlite3
    ports:
      - 5000:5000
    environment:
      GUNICORN_ARGS: '--reload'
      DB_FILE: /usr/src/FinanceManager.sqlite3
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile.develop
    stdin_open: true
    tty: true
    volumes:
      - ./app:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true