version: '3.7'

services:
  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    volumes:
      - ./db/FinanceManager.sqlite3:/usr/src/FinanceManager.sqlite3
    expose:
      - '5000'
    environment:
      GUNICORN_ARGS: '--limit-request-line 65536 --limit-request-field_size 65536'
      DB_FILE: /usr/src/FinanceManager.sqlite3
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:80