version: '3.7'

services:
  app:
    container_name: app
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/usr/src/app
      - ./db/FinanceManager.sqlite3:/usr/src/FinanceManager.sqlite3
    ports:
      - 5000:5000
    environment:
      GUNICORN_ARGS: '--reload'
      DB_FILE: /usr/src/FinanceManager.sqlite3
  web:
    container_name: web
    build:
      context: ./web
      dockerfile: Dockerfile.develop
    stdin_open: true
    tty: true
    volumes:
      - ./web:/usr/share/nginx/html
      - /usr/share/nginx/html/node_modules
    ports:
      - 8080:80
    environment:
      - CHOKIDAR_USEPOLLING=true
